# Uncomment and define the configuration variables below
# GMAIL_USERNAME: 'example'
# GMAIL_PASSWORD: 'example'
# SECRET_TOKEN: 'example'
# SENDGRID_USERNAME: 'example'
# SENDGRID_PASSWORD: 'example'

